### ISSUE TITLE
[Suggestion] Potential integration with Mare Synchronos

### ISSUE THREAD

**Issue by MadamLizard** [Glyceri/FFXIVPetRenamer#10]
This plugin is really great for RP, but I would if it could be integrated with Mare Synchronos so that my other friends can automatically see it without having to export and import names every time. It seems this has been asked about in the Mare Synchronos Discord before, and the answer seems to be that there needs to be some API integration between the two developers. I don't know exactly the full process but I hope this is something that's possible!

**Comment by Glyceri** [comment]
Hi MadamLizard! My hope/plan since day 1 has been that Pet Nicknames would integrate with Mare Synchronos and so I have had the backend API ready for about a year now. There have been many (fruitless) talks with the Mare Synchronos dev about it so far, and it'll come "eventually". Very soon after the 7.0 release I will start working on an upgraded version of the plogon! After that has released and Mare is up and running again; presumably around the same time; I want to really push the talks again and get Pet Nicknames integrated into Mare Synchronos.

**Comment by MadamLizard** [comment]
That is a great thing to hear!! Well, less great that talks have been fruitless so far, but I am pleased that you have worked on it and retain interest in integration. I suppose once the Dawntrail plugin update rush has calmed itself, I'll bring it up in the Mare Discord so that there's more visible demand for the developer to see. Is there anything else I can do to assist on that front?

**Comment by Glyceri** [comment]
Thank you! Honestly, I think the main problem is the demand is not really visible to the mare dev, only to me. Mentioning it would be of great help!

**Comment by Glyceri** [comment]
**Update:**
Development is [Actively in Progres](https://github.com/Penumbra-Sync/client/pull/74).

I'll lock the issue in case someone stumbles upon it, and close it when it's released.

_Important to know is for this release Pet Nicknames becomes a [third party plugin](https://raw.githubusercontent.com/Glyceri/FFXIVPetRenamer/main/PetNicknames.json) and will need to be installed manually._
_(Or [Sea of Stars](https://github.com/Ottermandias/SeaOfStars) potentially)._
_I will also ban the latest 1.0 release in dalamud and completely remove it from the official launcher._
