### ISSUE TITLE
[Suggestion] Allow renaming of characters?

### ISSUE THREAD

**Issue by emberglowo** [Glyceri/FFXIVPetRenamer#14]
So, it'd be really cool if we could extend the pet-renaming functionality to players as well (and, if they're synced with us, they'd see it too) - for the RP community, it'd let us pretend to be NPCs by glamouring as them and setting our name to, e.g. "Maelstrom Soldier".

Doable? Desired?

**Comment by Glyceri** [comment]
I'm slowly working on this [plugin](https://github.com/Glyceri/PlayerNicknames). 

Player Nicknames is highly debated topic and because of that it will NEVER be integrated into Pet Nicknames. It will also be third party.

I cannot give a timeframe but it definitely won't release within this year as I am busy. I also cannot promise it will ever release, but it definitely is in the works and I'm slowly adding to it. (I need to switch the old Pet Framework to the new and quite frankly I just don't feel like doing it just yet, this is why its so delayed). 

It will never have Mare sync, this discusion has been had and deemed problematic by both Dark and I. It will probably have manual sync.
